// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as taskresult$0 from "../taskresult/models.js";

export interface Log {
    "time": string;
    "level": string;
    "message": string;
}

export interface Record {
    "id": string;
    "sourceTaskID": string;
    "kind": string;
    "root": string;
    "scanListID": string;
    "phase": string;
    "startedAt": string;
    "finishedAt": string;
    "total": number;
    "completed": number;
    "succeeded": number;
    "failed": number;
    "skipped": number;
    "results": taskresult$0.Result[] | null;
    "logs": Log[] | null;
}

export interface Summary {
    "id": string;
    "sourceTaskID": string;
    "kind": string;
    "root": string;
    "scanListID": string;
    "phase": string;
    "startedAt": string;
    "finishedAt": string;
    "total": number;
    "completed": number;
    "succeeded": number;
    "failed": number;
    "skipped": number;
}
