// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Remote {
    "name": string;
    "url": string;
    "github": boolean;
}

export interface Repository {
    "path": string;
    "name": string;
    "branch": string;
    "upstream": string;
    "remotes": Remote[] | null;
    "changed": number;
    "ahead": number;
    "behind": number;
    "bare": boolean;
    "detached": boolean;
    "mergeInProgress": boolean;
    "lastCommit": string;
    "fetchStatus": string;
    "error": string;
}
