// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DiscardBackup {
    "id": string;
    "repository": string;
    "createdAt": string;
    "files": string[] | null;
    "ready": boolean;
}

export interface DiscardFile {
    "path": string;
    "fingerprint": string;
}

export interface DiscardPreview {
    "path": string;
    "branch": string;
    "head": string;
    "files": DiscardFile[] | null;
}

/**
 * MergePreview pins both sides of a confirmation to immutable commit IDs.
 */
export interface MergePreview {
    "path": string;
    "action": string;
    "branch": string;
    "head": string;
    "target": string;
    "targetHead": string;
    "ahead": number;
    "behind": number;
    "diverged": boolean;
}

export interface Remote {
    "name": string;
    "url": string;
    "github": boolean;
}

export interface Repository {
    "path": string;
    "name": string;
    "branch": string;
    "upstream": string;
    "remotes": Remote[] | null;
    "changed": number;
    "ahead": number;
    "behind": number;
    "bare": boolean;
    "detached": boolean;
    "mergeInProgress": boolean;
    "lastCommit": string;
    "fetchStatus": string;
    "syncStatus": string;
    "lastSuccessfulFetch": string;
    "error": string;
}
