// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Failure is safe to expose to the UI; Cause remains private and preserves cancellation.
 */
export interface Failure {
    "category": string;
    "stage": string;
    "retryable": boolean;
    "message": string;
    "detail": string;
}

export interface Result {
    "taskID": string;
    "kind": string;
    "path": string;
    "branch": string;
    "stage": string;
    "status": string;
    "attempts": number;
    "startedAt": string;
    "finishedAt": string;
    "durationMS": number;
    "networkSucceeded": boolean;
    "failure": Failure | null;
}
