// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface List {
    "scheduled": boolean;
    "intervalMinutes": number;
    "id": string;
    "name": string;
    "roots": string[] | null;
    "excludes": string[] | null;
}
