// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as taskresult$0 from "../taskresult/models.js";

export interface State {
    "busy": boolean;
    "status": string;
    "strategy": string;
    "remote": string;
    "startedAt": string;
    "finishedAt": string;
    "steps": Step[] | null;
}

export interface Step {
    "name": string;
    "status": string;
    "durationMS": number;
    "info": string;
    "failure": taskresult$0.Failure | null;
}
