// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService owns one cancellable task and exposes immutable snapshots to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops the running task. Fetch operations already completed are retained.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(159822507);
}

/**
 * ChooseDirectory opens the native directory picker. An empty result means cancelled.
 */
export function ChooseDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3405243763);
}

/**
 * GetState returns copies so a concurrent task cannot mutate a frontend response.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(4064312392);
}

/**
 * StartFetch accepts only repositories from the current scan, deduplicating selections.
 */
export function StartFetch(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(580180265, paths);
}

/**
 * StartScan validates the root and starts discovery without blocking the UI.
 */
export function StartScan(root: string): $CancellablePromise<void> {
    return $Call.ByID(1368166774, root);
}
