// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService owns one cancellable task and exposes immutable snapshots to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gitengine$0 from "./internal/gitengine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scansettings$0 from "./internal/scansettings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as taskresult$0 from "./internal/taskresult/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops the running task. Fetch operations already completed are retained.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(159822507);
}

/**
 * ChooseDirectory opens the native directory picker. An empty result means cancelled.
 */
export function ChooseDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3405243763);
}

export function GetBranches(path: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3919711711, path);
}

/**
 * GetFetchResults retains the last ten completed fetch tasks for retry provenance.
 */
export function GetFetchResults(taskID: string): $CancellablePromise<taskresult$0.Result[] | null> {
    return $Call.ByID(468996345, taskID);
}

export function GetScanLists(): $CancellablePromise<scansettings$0.List[] | null> {
    return $Call.ByID(1918790747);
}

/**
 * GetState returns copies so a concurrent task cannot mutate a frontend response.
 */
export function GetState(): $CancellablePromise<$models.State> {
    return $Call.ByID(4064312392);
}

/**
 * PreviewMerge is read-only and validates the current scanned scope.
 */
export function PreviewMerge(path: string, action: string, target: string): $CancellablePromise<gitengine$0.MergePreview> {
    return $Call.ByID(2310478365, path, action, target);
}

export function RemoveScanList(id: string): $CancellablePromise<void> {
    return $Call.ByID(2551141512, id);
}

/**
 * RetryFailed retries errors only. A successful fetch with a failed refresh never fetches again.
 */
export function RetryFailed(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(1171788232, taskID);
}

export function SaveScanList(list: scansettings$0.List): $CancellablePromise<scansettings$0.List> {
    return $Call.ByID(1032563213, list);
}

/**
 * StartAction executes only an explicit single-repository action selected in the UI.
 */
export function StartAction(path: string, action: string, target: string, confirmed: boolean): $CancellablePromise<void> {
    return $Call.ByID(481400661, path, action, target, confirmed);
}

/**
 * StartFetch accepts only repositories from the current scan, deduplicating selections.
 */
export function StartFetch(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(580180265, paths);
}

export function StartMerge(preview: gitengine$0.MergePreview, strategy: string, confirmed: boolean): $CancellablePromise<void> {
    return $Call.ByID(4042492005, preview, strategy, confirmed);
}

/**
 * StartScan validates the root and starts discovery without blocking the UI.
 */
export function StartScan(root: string): $CancellablePromise<void> {
    return $Call.ByID(1368166774, root);
}

export function StartScanList(id: string): $CancellablePromise<void> {
    return $Call.ByID(4230096354, id);
}
