// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gitengine$0 from "./internal/gitengine/models.js";

export interface LogEntry {
    "id": number;
    "time": string;
    "level": string;
    "message": string;
}

export interface State {
    "busy": boolean;
    "kind": string;
    "phase": string;
    "root": string;
    "current": string;
    "visited": number;
    "completed": number;
    "total": number;
    "succeeded": number;
    "failed": number;
    "skipped": number;
    "startedAt": string;
    "finishedAt": string;
    "repositories": gitengine$0.Repository[] | null;
    "logs": LogEntry[] | null;
}

export interface UpdateState {
    "version": string;
    "repository": string;
    "platform": string;
    "phase": string;
    "busy": boolean;
    "latestVersion": string;
    "notes": string;
    "written": number;
    "total": number;
    "authSource": string;
    "checkedAt": string;
    "error": string;
}
