// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService presents the Wails updater through the application's own UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel leaves the current executable unchanged and stops checking/downloading.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(4198371898);
}

/**
 * GetState contains status only; it never includes the token used for requests.
 */
export function GetState(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(1020347649);
}

/**
 * Restart prevents new Git tasks while Wails starts the replacement helper.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(3205679179);
}

/**
 * StartCheck checks stable public GitHub releases without a login or API token.
 */
export function StartCheck(): $CancellablePromise<void> {
    return $Call.ByID(1184951764);
}

/**
 * StartDownload downloads and verifies the pending executable; it does not restart.
 */
export function StartDownload(): $CancellablePromise<void> {
    return $Call.ByID(2790218660);
}
